# Generated by Django 6.0 on 2025-12-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=160, verbose_name='Resumo (SEO)'),
        ),
    ]
