# Generated by Django 6.0 on 2025-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_author_alter_post_created_at_alter_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome público da categoria.', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], db_index=True, default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
