# Generated by Django 6.0 on 2025-12-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_name_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.URLField(blank=True, help_text='URL da imagem (Cloudinary/CDN). Campo principal.', verbose_name='Imagem de destaque (URL)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Conteúdo principal do post (HTML permitido).', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Campo legado. Será removido no passo 3.', null=True, upload_to='posts/', verbose_name='Imagem local (legado)'),
        ),
    ]
