# Generated by Django 6.0 on 2025-12-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_featured_image_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.URLField(blank=True, help_text='URL da imagem (Cloudinary/CDN).', max_length=500, verbose_name='Imagem de destaque (URL)'),
        ),
    ]
