# Generated by Django 6.0 on 2025-12-24 13:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(help_text='Conteúdo HTML gerado pelo editor.', verbose_name='Conteúdo'),
        ),
    ]
