# Generated by Django 6.0 on 2025-12-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Informe apenas o ID do vídeo (ex: dQw4w9WgXcQ)', max_length=50, null=True, verbose_name='Vídeo do YouTube'),
        ),
    ]
