# Generated by Django 6.0 on 2025-12-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título exibido no box.', max_length=150, verbose_name='Título do CTA')),
                ('description', models.TextField(blank=True, help_text='Texto opcional para reforçar o CTA.', verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='Link')),
                ('anchor_text', models.CharField(help_text='Texto do link para SEO interno.', max_length=150, verbose_name='Texto âncora (SEO)')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Abrir em nova aba')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CTA (SEO)',
                'verbose_name_plural': 'CTAs (SEO)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ctas',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.cta', verbose_name='CTAs de SEO'),
        ),
    ]
