# Generated by Django 5.2.7 on 2026-07-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_cta_post_ctas"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_slug_cdb902_idx",
        ),
    ]
