# Generated by Django 5.2.7 on 2026-10-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EbookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ebooks/categories/",
                        verbose_name="Imagem",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Categoria de ebook",
                "verbose_name_plural": "Categorias de ebooks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("short_description", models.TextField(verbose_name="Descrição curta")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "cover",
                    models.ImageField(upload_to="ebooks/covers/", verbose_name="Capa"),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=150, verbose_name="Autor"),
                ),
                (
                    "google_drive_url",
                    models.URLField(verbose_name="URL do Google Drive"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ebooks",
                        to="ebooks.ebookcategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ebook",
                "verbose_name_plural": "Ebooks",
                "ordering": ["-created_at"],
            },
        ),
    ]
