# Generated by Django 5.2.7 on 2026-10-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebook",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Preço original",
            ),
        ),
        migrations.AddField(
            model_name="ebook",
            name="purchase_url",
            field=models.URLField(blank=True, verbose_name="URL de compra"),
        ),
        migrations.AddField(
            model_name="ebook",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Preço promocional",
            ),
        ),
        migrations.AlterField(
            model_name="ebook",
            name="google_drive_url",
            field=models.URLField(blank=True, verbose_name="URL do Google Drive"),
        ),
    ]
